services:
  mc:
    image: itzg/minecraft-server:latest
    container_name: minecraft-server
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      MEMORY: "8G"
      INIT_MEMORY: "8G"
      MAX_MEMORY: "8G"
      MAX_PLAYERS: "10"
    volumes:
      - ./minecraft-data:/data:Z
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro